Repository SuiteCRM/SuiteCRM-Core, pull requests merged in 2022-10, with the labels that each got.

#132 Fix #131 - Cannot login if username is associated with deleted user
  core/modules/Users/Repository/UserRepository.php
Labels: Status:Assessed

#158 Fixed #155 - Dynamic Dropdown using parent enum labels instead of values
  core/app/core/src/lib/fields/base/base-enum.component.ts
Labels: Status:Assessed, Hacktoberfest, Hacktoberfest-Accepted

#164 Fix #59 "Bad data passed in;" When trying to forward reply to emails
  public/legacy/modules/Emails/metadata/detailviewdefs.php
Labels: Hacktoberfest, Hacktoberfest-Accepted
